### ISSUE TITLE
rsync频繁中断

### ISSUE THREAD

**Issue by lovechang1986** [tuna/tunasync#101]
最近在使用时总是中断，或因为timeout或因为各种其他原因，每次重启同步就全部再下载一遍，请问如何实现断点续传功能？

**Comment by z4yx** [comment]
你的场景是用tunasync调用rsync去同步数据吗？按我的理解，rsync是个差异同步工具，不会每次全部下载一遍的。

**Comment by lovechang1986** [comment]
我是使用tunasync调用rsync去同步的，可能我理解有误，但是每次开始同步之后就会非常的慢，可能并没有下载，但是比对过程太慢，似乎和下载一样。

**Comment by z4yx** [comment]
你看看tunasync记录的rsync日志，里面会列出来下载了那些文件，据此判断是否有文件重新下载。

**Comment by lovechang1986** [comment]
不知为何我找不到rsync的日志。
我的worker配置如下：
[[mirrors]]
name = "anaconda"
provider = "rsync"
upstream = "rsync://mirrors.tuna.tsinghua.edu.cn/anaconda/"
use_ipv6 = false
得到的tunasync的worker错误记录如下：
rsync: connection unexpectedly closed (46533430 bytes received so far) [receiver]rsync: writefd_unbuffered failed to write 4 bytes to socket [generator]: Connection reset by peer (104)
rsync error: error in rsync protocol data stream (code 12) at io.c(1532) [generator=3.0.9]
rsync error: error in rsync protocol data stream (code 12) at io.c(605) [receiver=3.0.9]
目前基本上每次都是在同步archive文件夹的时候出错的，然后无法继续同步后面的文件夹了。。

**Comment by lovechang1986** [comment]
此外，使用rsync时，如何添加其他参数呢？

**Comment by z4yx** [comment]
类似 https://github.com/tuna/tunasync/blob/master/docs/zh_CN/workers.conf 这样配置`log_dir`之后，日志就会放到，每个任务单独的文件夹下面。

 rsync能不能通过配置文件加额外参数，我不确定。  @shankerwangmiao 知道吗？

**Comment by z4yx** [comment]
目前不能直接通过配置文件支持，要额外参数可以指定`command=xxx.sh`，也就是把rsync换成自己的脚本，在脚本里面添加额外参数。

**Comment by kirov-qh** [comment]
我遇到了类似的问题，看 rsync 的返回错误码有10和12。想知道在上游是否有相应的流量控制策略会直接断开 rsync 连接。

**Comment by shankerwangmiao** [comment]
有些上游的确可能有类似的配置

**Comment by Zhang-Xianglong** [comment]
@lovechang1986 @kirov-qh 请问你们的问题解决了吗？我遇到了相似的问题。https://github.com/tuna/tunasync/issues/119#issue-628267032
