### ISSUE TITLE
能否临时开通一下pypi源的rsync下载？

### ISSUE THREAD

**Issue by githubitnow** [tuna/tunasync#103]
如题，我在某事业单位的内网架设了一套开源镜像，给广大用户提供各类系统、应用的镜像

贵站的其它源都开放了rsync同步，用tunasync做已经很方便了，感谢各位的辛勤劳动！

了解了一下，pypi的源，要自行去更新的话，需要架设独立的服务程序，而且还不是很稳定

不知能否临时开通一下pypi的rsync下载？

**Comment by shankerwangmiao** [comment]
Pypi 由于文件数目过多，因此无法启用 Rsync 同步。
