### ISSUE TITLE
树莓派4上编译出现错误

### ISSUE THREAD

**Issue by TopSWorld** [tuna/tunasync#105]
你好，在树莓派上编译出现如下错误：
# github.com/dennwc/btrfs
../go/pkg/mod/github.com/dennwc/btrfs@v0.0.0-20190517175702-d917b30ff035/utils.go:18:19: constant 2435016766 overflows int32
make: *** [Makefile:8: get] Error 2
请问有对应的解决方法吗？？

**Comment by z4yx** [comment]
这是 dennwc/btrfs 项目的问题，请向他们报告。
