### ISSUE TITLE
tunasync能否增加定时同步的功能

### ISSUE THREAD

**Issue by atomse** [tuna/tunasync#106]
有些源定时修改数据，想问tunasync能否做到定时同步（像crontab一样）

如果能，如何修改配置文件实现这一功能？
如果不能，是否有必要增加这一功能？

**Comment by shankerwangmiao** [comment]
tunasync 不能作到绝对准时进行同步，而是在一次同步结束之后隔一定时间后再启动同步。同时会受到同时启动的任务数量的限制。

增加这一功能必要性不强，可以采取定时调用 tunasynctl 启动同步任务的方式处理。
