### ISSUE TITLE
”常用发行版和应用工具安装包下载“页面无法加载

### ISSUE THREAD

**Issue by AFGXF** [tuna/tunasync#111]
“常用发行版 iso 和应用工具安装包直接下载”页面加载不出来

![image](https://user-images.githubusercontent.com/54260142/76843199-651c3b00-6876-11ea-87db-76361522ab47.png)

浏览器:FireFox 74.0 & Microsoft Edge 旧版

今天上午就有这种情况

是服务器维护吗

**Comment by z4yx** [comment]
服务器配置问题，已修复。
