### ISSUE TITLE
Add MirrorStatus.LastStarted property

### ISSUE THREAD

**Issue by phy25** [tuna/tunasync#115]
I would like to propose adding a new status property `LastStarted` saving `textTime` and the respective `LastStartedTs` property for each job, which will be updated in Server.updateJobOfWorker during the following state change condition:

- `status.Status` is in PreSyncing (AFAIK this is a mandatory state..?), and
-  `curStatus.Status` is not in PreSyncing

I think I can develop it, but just want to know if there is any interest in this functionality (and would probably be merged) before I do so.

**Comment by z4yx** [comment]
It's a good feature. With these fields, our website can show how long the job has been taken. 

PreSyncing is a mandatory state, you can rely on that.

Thanks for helping us.
