### ISSUE TITLE
Ubuntu源 重复同步

### ISSUE THREAD

**Issue by Zhang-Xianglong** [tuna/tunasync#119]
#### 发生了什么（What happened）
rsync超时或系统重启（导致tunasync重启），发现本次同步的文件在上次的同步日志中已经出现了。目前发现的是ustc下Ubuntu源的dists、pool、indices目录。

#### 期望的现象（What you expected to happen）
同步中断或重启时，已同步的文件不应再次同步。

#### 如何重现（How to reproduce it）
ps -ef看到的实际命令为rsync -aHvh --no-o --no-g --stats --exclude .tmp/ --delete --delete-after --delay-updates --safe-links --timeout=120 rsync://rsync.mirrors.ustc.edu.cn/ubuntu/ /mirrors/ubuntu

#### 您的环境（Environment）
- 操作系统（OS Version）：CentOS 7
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by Zhang-Xianglong** [comment]
@z4yx 是否有优化的方法？rsync有时会超时，我在配置文件中配置了timeout参数，但并不起作用。

**Comment by z4yx** [comment]
我以前也查过，似乎没有参数能改变rsync的这个行为。
timeout=n (秒）是最近新增的参数，目前还没有大范围测试过，如果你发现有bug，请开下debug日志，然后新开issue，我们一起来研究下。

**Comment by z4yx** [comment]
顺便说一下，rsync自己的timeout参数不是我们通常理解的超时时间。而是每次recv的超时，因此一般不起作用。

**Comment by Zhang-Xianglong** [comment]
@z4yx 谢谢您详尽的回复。
```
dists/xenial-updates/main/signed/linux-hwe-amd64/4.15.0-99.100~16.04.1/
dists/xenial-updates/main/signed/linux-hwe-amd64/4.15.0-99.100~16.04.1/SHA256SUMS
dists/xenial-updates/main/signed/linux-hwe-amd64/4.15.0-99.100~16.04.1/SHA256SUMS.gpg
[generator] io timeout after 120 seconds -- exiting
rsync error: timeout in data send/receive (code 30) at io.c(195) [generator=3.1.2]
rsync error: received SIGUSR1 (code 19) at main.c(1429) [receiver=3.1.2]
rsync error: Timeout in data send/receive
```
以上是`rsync -aHvh --no-o --no-g --stats --exclude .tmp/ --delete --delete-after --delay-updates --safe-links --timeout=120 rsync://rsync.mirrors.ustc.edu.cn/ubuntu/ /mirrors/ubuntu`出错的输出，超时并不总发生在指定文件的同步上，但都发生在dists、pool、indices这几个目录（目录太大了？？？）。
但这个现象并没有出现在CentOS源（tuna）和EPEL源（ustc）的同步任务中，可能是因为我并未关注，因为这两个源已经完成了同步。

以下来自rsync的manpage
```
--timeout=SECONDS       set I/O timeout in seconds
--timeout=TIMEOUT
This option allows you to set a maximum I/O timeout in seconds. If no data is transferred for the specified time then rsync will exit. The default is 0, which means no timeout.
--delete-before
Request that the file-deletions on the receiving side be done before the transfer starts. See --delete (which is implied) for more details on file-deletion.
Deleting before the transfer is helpful if the filesystem is tight for space and removing extraneous files would help to make the transfer possible. However, it does introduce a delay before the start of the transfer, and this delay might cause the transfer to timeout (if --timeout was specified). It also forces rsync to use the old, non-incremental recursion algorithm that requires rsync to scan all the files in the transfer into memory at once (see --recursive).
```
@z4yx 您的意思是tunasync的timeout=n (秒）参数需要更新到最新版tunasync才可以使用吗？将它设置为0是否可以解决问题呢？

我可以猜测ustc对每天的同步量进行了限制？或者是我的网络不稳定造成的？

**Comment by z4yx** [comment]
你遇到的问题应该是网络中断或者上游因为压力过大断开了连接。
你可以试试tuna的新站点：rsync://mirrors.bfsu.edu.cn/ubuntu/
tunasync的timeout=n (秒）参数是最新版才有的，但是不解决你的问题。这个参数是防止rsync有时候会卡死不退出，比如我们遇到过它运行了一周，但是并没有在传输文件。

**Comment by Zhang-Xianglong** [comment]
@z4yx 好的 谢谢。
在旧的worker上修改upstream，会导致已同步的数据清空吗。还是创建一个新的worker？

**Comment by z4yx** [comment]
不会，rsync照常进行差异同步。

**Comment by Zhang-Xianglong** [comment]
@z4yx 好的，谢谢。

**Comment by Zhang-Xianglong** [comment]
@z4yx 
```
[generator] io timeout after 120 seconds -- exiting
rsync error: timeout in data send/receive (code 30) at io.c(195) [generator=3.1.2]
rsync error: received SIGUSR1 (code 19) at main.c(1429) [receiver=3.1.2]
rsync error: Timeout in data send/receiv
```
`rsync://mirrors.bfsu.edu.cn/ubuntu/`的速度确实快了不少。但不幸的事情还是发生了。
在同步了4G-6G的数据

**Comment by z4yx** [comment]
建议你先手工运行rsync命令，不加timeout参数，试试是不是断开。
bfsu负载不高，也不会在某个时刻故意断开。我觉得更有可能你的网络中存在NAT设备，对于TCP连接的时间或者传输数据量有限制。

**Comment by Zhang-Xianglong** [comment]
@z4yx 好的。我尝试一下。

**Comment by Zhang-Xianglong** [comment]
@z4yx 

可喜的是，手工运行确实同步了更多的数据。不幸的是，又发生了其他的问题。
```
rsync: read error: Connection reset by peer (104)
rsync error: error in socket IO (code 10) at io.c(785) [receiver=3.1.2]
rsync: [generator] write error: Broken pipe (32)
rsync error: error in socket IO (code 10) at io.c(820) [generator=3.1.2]
```

**Comment by z4yx** [comment]
这么看来，你那边到镜像站的网络确实不够稳定，网络问题只有想其它办法解决了。

**Comment by Zhang-Xianglong** [comment]
和 https://github.com/tuna/tunasync/issues/101#issuecomment-548349057 的问题一样吗？毕竟Ubuntu镜像远大于CentOS和EPEL，相应的文件列表也必然更大。
我查了一下可能是服务端rsync服务的配置问题？您那边有相应的日志吗？

**Comment by z4yx** [comment]
有可能，我们经常接到这类网络问题报告，主要出现在非教育网、非公网IP的用户上，这类问题不是我们能解决的。

**Comment by Zhang-Xianglong** [comment]
> 这么看来，你那边到镜像站的网络确实不够稳定，网络问题只有想其它办法解决了。

@z4yx 这个不太清除，怎么分析这个网络问题呢？
我也在北京，并且CentOS和EPEL的源都同步成功了，Ubuntu之前也同步了约800G。
猜想会不会和Ubuntu镜像太大，导致相应的同步时间限制超出了服务器端rsync的配置？

**Comment by z4yx** [comment]
我确认过服务器上没有任何超时配置，所以很可能是网络中的NAT、防火墙这类4层设备在作怪。这种问题很难调查，就算证实了也没法改变。

**Comment by Zhang-Xianglong** [comment]
@z4yx 好的 谢谢。我再尝试一下吧。

**Comment by Zhang-Xianglong** [comment]
@z4yx 我有一个想法。
`rsync -aHvh --no-o --no-g --stats --exclude .tmp/ --delete --delete-after --delay-updates --safe-links --timeout=120 rsync://rsync.mirrors.ustc.edu.cn/ubuntu/ /mirrors/ubuntu`是tunasync调用的指令。Ubuntu镜像源较大-->同步时间较长-->链接被NAT设备断开，我是否可以在此基础上增加--exclude参数，执行多次，对子目录分别进行同步。这种方式是否可行？

**Comment by shankerwangmiao** [comment]
建议首次同步可以使用你希望的任何方法同步好就可以，之后的增量同步一般由于量不大，出现类似问题的可能性不大。

**Comment by Zhang-Xianglong** [comment]
@shankerwangmiao 非常感谢。
