### ISSUE TITLE
Release v0.6.3 mirrors.timeout配置不起作用

### ISSUE THREAD

**Issue by Zhang-Xianglong** [tuna/tunasync#121]
你好。

mirrors.timeout配置预料中映射到rsync的--timeout参数，是这样吗？
我试了一下，并不起作用。

**Comment by Zhang-Xianglong** [comment]
@z4yx

**Comment by z4yx** [comment]
不是，这个timeout 用于限制 rsync 进程的运行时间。
--timeout=120 参数目前是hard-code的，如果有必要，我可以再加个配置项。

**Comment by Zhang-Xianglong** [comment]
@z4yx 好的，非常感谢。

如果可以配置rsync的--timeout参数，当然更好。看您这边的评估。
