### ISSUE TITLE
rsync的timeout参数是否可调？超时后是否可以重试？

### ISSUE THREAD

**Issue by canghaiwuhen** [tuna/tunasync#122]
默认参数--timeout=120，是否有参数可以调整？
超时后是否可以重试？
比如ustc的rsync限制了总连接数，当前如果被别人占满了，就无法连接，可否增加一个重试次数的参数？
虽然可以通过缩短同步周期来实现重试的目的，但不是长久之计

**Comment by z4yx** [comment]
最新版本支持配置项 `rsync_timeout=n` 用于修改默认的120
重试次数通过 `retry=n` 来配置

**Comment by canghaiwuhen** [comment]
> 最新版本支持配置项 `rsync_timeout=n` 用于修改默认的120
> 重试次数通过 `retry=n` 来配置

好的 感谢！
