### ISSUE TITLE
manager经常报错退出

### ISSUE THREAD

**Issue by canghaiwuhen** [tuna/tunasync#124]
mirror:~# tail -f /opt/mirrors/tunasync/log/manager.log 
[20-06-15 12:31:44][NOTICE] Job [lede] @<lede_worker> pre-syncing
[20-06-15 12:31:44][NOTICE] Job [ubuntu] @<ubuntu_worker> pre-syncing
[20-06-15 12:31:44][NOTICE] Job [kali] @<kali_worker> starts syncing
[20-06-15 12:31:44][NOTICE] Job [archlinux] @<archlinux_worker> starts syncing
[20-06-15 12:31:44][NOTICE] Job [raspbian] @<raspbian_worker> pre-syncing
[20-06-15 12:31:44][NOTICE] Job [lede] @<lede_worker> starts syncing
[20-06-15 12:31:44][NOTICE] Job [raspbian] @<raspbian_worker> starts syncing
[20-06-15 12:31:44][NOTICE] Job [ubuntu] @<ubuntu_worker> starts syncing
[20-06-15 12:31:49][NOTICE] Job [ubuntu-old-releases] @<ubuntu_worker> pre-syncing
[20-06-15 12:31:49][NOTICE] Job [ubuntu-old-releases] @<ubuntu_worker> starts syncing
unexpected fault address 0x7fbbe0efd008
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7fbbe0efd008 pc=0x997894]

goroutine 106 [running]:
runtime.throw(0xb42c43, 0x5)
        /usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc0003734a8 sp=0xc000373478 pc=0x430e62
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:391 +0x455 fp=0xc0003734d8 sp=0xc0003734a8 pc=0x4469c5
github.com/boltdb/bolt.(*Cursor).search(0xc000373670, 0xc0003736d9, 0x7, 0x7, 0x4)
        /root/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/cursor.go:255 +0x64 fp=0xc000373578 sp=0xc0003734d8 pc=0x997894
github.com/boltdb/bolt.(*Cursor).seek(0xc000373670, 0xc0003736d9, 0x7, 0x7, 0x10, 0xaab260, 0x7fbbe0ef9001, 0xc000363830, 0xc000373690, 0x9a15dc, ...)
        /root/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/cursor.go:159 +0x7d fp=0xc0003735e8 sp=0xc000373578 pc=0x99711d
github.com/boltdb/bolt.(*Bucket).Bucket(0xc00040c718, 0xc0003736d9, 0x7, 0x7, 0x1000)
        /root/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/bucket.go:112 +0xd4 fp=0xc0003736a0 sp=0xc0003735e8 pc=0x993144
github.com/boltdb/bolt.(*Tx).Bucket(...)
        /root/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/tx.go:101
github.com/tuna/tunasync/manager.(*boltAdapter).GetWorker.func1(0xc00040c700, 0xc000068800, 0xc00040c700)
        /root/tunasync/manager/db.go:88 +0x8d fp=0xc000373740 sp=0xc0003736a0 pc=0x9ae5fd
github.com/boltdb/bolt.(*DB).View(0xc00024c1e0, 0xc0003737f0, 0x0, 0x0)
        /root/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/db.go:629 +0xa8 fp=0xc0003737c8 sp=0xc000373740 pc=0x99a5e8
github.com/tuna/tunasync/manager.(*boltAdapter).GetWorker(0xc00021bb20, 0xc0003ad14e, 0xd, 0xb41660, 0x2, 0xc0003ad14e, 0xd, 0xc0003abd01, 0x432c5c, 0xc000373870, ...)
        /root/tunasync/manager/db.go:87 +0x88 fp=0xc000373820 sp=0xc0003737c8 pc=0x9a7448
github.com/tuna/tunasync/manager.(*Manager).workerIDValidator(0xc00025eae0, 0xc000225a00)
        /root/tunasync/manager/middleware.go:25 +0xa3 fp=0xc0003738c0 sp=0xc000373820 pc=0x9a7fa3
github.com/tuna/tunasync/manager.(*Manager).workerIDValidator-fm(0xc000225a00)
        /root/tunasync/manager/middleware.go:23 +0x34 fp=0xc0003738e0 sp=0xc0003738c0 pc=0x9aff14
github.com/gin-gonic/gin.(*Context).Next(0xc000225a00)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 +0x3b fp=0xc000373900 sp=0xc0003738e0 pc=0x90898b
github.com/tuna/tunasync/manager.contextErrorLogger(0xc000225a00)
        /root/tunasync/manager/middleware.go:20 +0x285 fp=0xc0003739b8 sp=0xc000373900 pc=0x9a7ee5
github.com/gin-gonic/gin.(*Context).Next(0xc000225a00)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 +0x3b fp=0xc0003739d8 sp=0xc0003739b8 pc=0x90898b
github.com/gin-gonic/gin.RecoveryWithWriter.func1(0xc000225a00)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/recovery.go:83 +0x64 fp=0xc000373a38 sp=0xc0003739d8 pc=0x91c0f4
github.com/gin-gonic/gin.(*Context).Next(0xc000225a00)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 +0x3b fp=0xc000373a58 sp=0xc000373a38 pc=0x90898b
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc00026eb40, 0xc000225a00)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/gin.go:403 +0x67a fp=0xc000373be0 sp=0xc000373a58 pc=0x91268a
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc00026eb40, 0xc48b00, 0xc00040c620, 0xc0003f2500)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/gin.go:364 +0x14e fp=0xc000373c18 sp=0xc000373be0 pc=0x911d7e
net/http.serverHandler.ServeHTTP(0xc0002861c0, 0xc48b00, 0xc00040c620, 0xc0003f2500)
        /usr/local/go/src/net/http/server.go:2802 +0xa4 fp=0xc000373c48 sp=0xc000373c18 pc=0x6e3af4
net/http.(*conn).serve(0xc000305400, 0xc4afc0, 0xc0003ead40)
        /usr/local/go/src/net/http/server.go:1890 +0x875 fp=0xc000373fc8 sp=0xc000373c48 pc=0x6df395
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000373fd0 sp=0xc000373fc8 pc=0x460e51
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2928 +0x384

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7fbbe0f161e8, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc000284218, 0x72, 0x0, 0x0, 0xb4496c)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc000284200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:384 +0x1f8
net.(*netFD).accept(0xc000284200, 0xc000206f70, 0x6e4a84, 0xc000286260)
        /usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc00021be20, 0x5ee6fa67, 0xc000206f70, 0x4c4ab6)
        /usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc00021be20, 0xc000206fc0, 0x18, 0xc000000180, 0x6e3fb4)
        /usr/local/go/src/net/tcpsock.go:261 +0x47
net/http.(*Server).Serve(0xc0002861c0, 0xc48840, 0xc00021be20, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2896 +0x280
net/http.(*Server).ListenAndServe(0xc0002861c0, 0xc0002861c0, 0xc0002071c8)
        /usr/local/go/src/net/http/server.go:2825 +0xb7
github.com/tuna/tunasync/manager.(*Manager).Run(0xc00025eae0)
        /root/tunasync/manager/server.go:120 +0x1b9
main.startManager(0xc0000caf20, 0x0, 0xc0000cae70)
        /root/tunasync/cmd/tunasync/tunasync.go:47 +0x1a2
github.com/urfave/cli.HandleAction(0xa58560, 0xb71cd0, 0xc0000caf20, 0xc0000caf20, 0x0)
        /root/go/pkg/mod/github.com/urfave/cli@v1.22.3/app.go:526 +0xbe
github.com/urfave/cli.Command.Run(0xb44f8c, 0x7, 0x0, 0x0, 0xc000260c40, 0x1, 0x1, 0xb51ac3, 0x1a, 0x0, ...)
        /root/go/pkg/mod/github.com/urfave/cli@v1.22.3/command.go:174 +0x51c
github.com/urfave/cli.(*App).Run(0xc00024a1c0, 0xc0000aa000, 0x4, 0x4, 0x0, 0x0)
        /root/go/pkg/mod/github.com/urfave/cli@v1.22.3/app.go:279 +0x725
main.main()
        /root/tunasync/cmd/tunasync/tunasync.go:227 +0xce6

goroutine 19 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:29 +0x41

**Comment by canghaiwuhen** [comment]
再次退出：
mirror:~# unexpected fault address 0x7f7c53c88008
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7f7c53c88008 pc=0x997894]

goroutine 188 [running]:
runtime.throw(0xb42c43, 0x5)
        /usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc0000554a8 sp=0xc000055478 pc=0x430e62
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:391 +0x455 fp=0xc0000554d8 sp=0xc0000554a8 pc=0x4469c5
github.com/boltdb/bolt.(*Cursor).search(0xc000055670, 0xc0000556d9, 0x7, 0x7, 0x6)
        /root/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/cursor.go:255 +0x64 fp=0xc000055578 sp=0xc0000554d8 pc=0x997894
github.com/boltdb/bolt.(*Cursor).seek(0xc000055670, 0xc0000556d9, 0x7, 0x7, 0x10, 0xaab260, 0x7f7c53c82001, 0xc000028110, 0xc000055690, 0x9a15dc, ...)
        /root/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/cursor.go:159 +0x7d fp=0xc0000555e8 sp=0xc000055578 pc=0x99711d
github.com/boltdb/bolt.(*Bucket).Bucket(0xc00027c2b8, 0xc0000556d9, 0x7, 0x7, 0x1000)
        /root/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/bucket.go:112 +0xd4 fp=0xc0000556a0 sp=0xc0000555e8 pc=0x993144
github.com/boltdb/bolt.(*Tx).Bucket(...)
        /root/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/tx.go:101
github.com/tuna/tunasync/manager.(*boltAdapter).GetWorker.func1(0xc00027c2a0, 0xc0000a8100, 0xc00027c2a0)
        /root/tunasync/manager/db.go:88 +0x8d fp=0xc000055740 sp=0xc0000556a0 pc=0x9ae5fd
github.com/boltdb/bolt.(*DB).View(0xc0002421e0, 0xc0000557f0, 0x0, 0x0)
        /root/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/db.go:629 +0xa8 fp=0xc0000557c8 sp=0xc000055740 pc=0x99a5e8
github.com/tuna/tunasync/manager.(*boltAdapter).GetWorker(0xc00021bac0, 0xc0000ee00e, 0xd, 0xb41660, 0x2, 0xc0000ee00e, 0xd, 0x7f7c514f8f01, 0x400, 0x7f7c512ffa00, ...)
        /root/tunasync/manager/db.go:87 +0x88 fp=0xc000055820 sp=0xc0000557c8 pc=0x9a7448
github.com/tuna/tunasync/manager.(*Manager).workerIDValidator(0xc0002726c0, 0xc000224000)
        /root/tunasync/manager/middleware.go:25 +0xa3 fp=0xc0000558c0 sp=0xc000055820 pc=0x9a7fa3
github.com/tuna/tunasync/manager.(*Manager).workerIDValidator-fm(0xc000224000)
        /root/tunasync/manager/middleware.go:23 +0x34 fp=0xc0000558e0 sp=0xc0000558c0 pc=0x9aff14
github.com/gin-gonic/gin.(*Context).Next(0xc000224000)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 +0x3b fp=0xc000055900 sp=0xc0000558e0 pc=0x90898b
github.com/tuna/tunasync/manager.contextErrorLogger(0xc000224000)
        /root/tunasync/manager/middleware.go:20 +0x285 fp=0xc0000559b8 sp=0xc000055900 pc=0x9a7ee5
github.com/gin-gonic/gin.(*Context).Next(0xc000224000)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 +0x3b fp=0xc0000559d8 sp=0xc0000559b8 pc=0x90898b
github.com/gin-gonic/gin.RecoveryWithWriter.func1(0xc000224000)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/recovery.go:83 +0x64 fp=0xc000055a38 sp=0xc0000559d8 pc=0x91c0f4
github.com/gin-gonic/gin.(*Context).Next(0xc000224000)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 +0x3b fp=0xc000055a58 sp=0xc000055a38 pc=0x90898b
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc000262b40, 0xc000224000)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/gin.go:403 +0x67a fp=0xc000055be0 sp=0xc000055a58 pc=0x91268a
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc000262b40, 0xc48b00, 0xc00027c0e0, 0xc000126300)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/gin.go:364 +0x14e fp=0xc000055c18 sp=0xc000055be0 pc=0x911d7e
net/http.serverHandler.ServeHTTP(0xc00027c1c0, 0xc48b00, 0xc00027c0e0, 0xc000126300)
        /usr/local/go/src/net/http/server.go:2802 +0xa4 fp=0xc000055c48 sp=0xc000055c18 pc=0x6e3af4
net/http.(*conn).serve(0xc0000ae320, 0xc4afc0, 0xc000020040)
        /usr/local/go/src/net/http/server.go:1890 +0x875 fp=0xc000055fc8 sp=0xc000055c48 pc=0x6df395
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000055fd0 sp=0xc000055fc8 pc=0x460e51
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2928 +0x384

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7f7c53c9f458, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc00027a198, 0x72, 0x0, 0x0, 0xb4496c)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc00027a180, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:384 +0x1f8
net.(*netFD).accept(0xc00027a180, 0xc0001eef70, 0x6e4a84, 0xc00027c260)
        /usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc00021bdc0, 0x5ee70e44, 0xc0001eef70, 0x4c4ab6)
        /usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc00021bdc0, 0xc0001eefc0, 0x18, 0xc000000180, 0x6e3fb4)
        /usr/local/go/src/net/tcpsock.go:261 +0x47
net/http.(*Server).Serve(0xc00027c1c0, 0xc48840, 0xc00021bdc0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2896 +0x280
net/http.(*Server).ListenAndServe(0xc00027c1c0, 0xc00027c1c0, 0xc0002071c8)
        /usr/local/go/src/net/http/server.go:2825 +0xb7
github.com/tuna/tunasync/manager.(*Manager).Run(0xc0002726c0)
        /root/tunasync/manager/server.go:120 +0x1b9
main.startManager(0xc0000cac60, 0x0, 0xc0000cabb0)
        /root/tunasync/cmd/tunasync/tunasync.go:47 +0x1a2
github.com/urfave/cli.HandleAction(0xa58560, 0xb71cd0, 0xc0000cac60, 0xc0000cac60, 0x0)
        /root/go/pkg/mod/github.com/urfave/cli@v1.22.3/app.go:526 +0xbe
github.com/urfave/cli.Command.Run(0xb44f8c, 0x7, 0x0, 0x0, 0xc000256b90, 0x1, 0x1, 0xb51ac3, 0x1a, 0x0, ...)
        /root/go/pkg/mod/github.com/urfave/cli@v1.22.3/command.go:174 +0x51c
github.com/urfave/cli.(*App).Run(0xc0002401c0, 0xc0000aa000, 0x4, 0x4, 0x0, 0x0)
        /root/go/pkg/mod/github.com/urfave/cli@v1.22.3/app.go:279 +0x725
main.main()
        /root/tunasync/cmd/tunasync/tunasync.go:227 +0xce6

goroutine 19 [syscall, 14 minutes]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:29 +0x41

**Comment by phy25** [comment]
tunasync 的版本是？

**Comment by canghaiwuhen** [comment]
> tunasync 的版本是？
mirror:~# tunasync --version
Version: 0.6.5
Git Hash: 45e5d900fbc6784aaf48a46f95d21880d35af3c5
Build Date: 2020-06-10 10:19:15 +0800 CST

**Comment by z4yx** [comment]
看起来出错的是BoltDB内部，建议你删除manager.db后重新运行。

**Comment by canghaiwuhen** [comment]
> 看起来出错的是BoltDB内部，建议你删除manager.db后重新运行。

好的，我试试

**Comment by canghaiwuhen** [comment]
看起来没问题了，跑了一晚上没出错，多谢
