### ISSUE TITLE
How can I sync CentOS7.8 only?

### ISSUE THREAD

**Issue by ZuoGuocai** [tuna/tunasync#128]
Hi, Dear Tunasync Team.  I want to  sync centos7.8  only  from upstream mirror. I do   the config  as the below. But failed.  How can I config in the worker.conf ?Thanks.

 ```
[[mirrors]]
name = "centos"
provider = "rsync"
upstream = "rsync://mirrors.tuna.tsinghua.edu.cn/centos/7.8.2003/"
use_ipv6 = false
```

**Comment by phy25** [comment]
What's the error message?

**Comment by ZuoGuocai** [comment]
I config  centos and  epel  both in the worker.conf. The epel job start  syncing successfully. But there is nothing message about centos7.8  job.  I check the  mirror data  directory  and find  nothing about centos  in the data directory neither.
```
[[mirrors]]
name = "centos7.8
provider = "rsync"
upstream = "rsync://mirrors.tuna.tsinghua.edu.cn/centos/7.8.2003/"
use_ipv6 = false
 
[[mirrors]]
name = "epel"
provider = "rsync"
upstream = "rsync://mirrors.tuna.tsinghua.edu.cn/epel/"
use_ipv6 = false
```

**Comment by shankerwangmiao** [comment]
Have you ever send a `reload` command to the tunasync daemon to reload your configuration?

**Comment by shankerwangmiao** [comment]
BTW, in `centos` repo, `centos/7` is a symbol link to the most recent minor version of CentOS 7. Currently, `7` is linked to `7.8.2003`. However, when a new minor version is released, the link will be pointed to it, and older minor versions will be removed, just like what can be seen in, for example, `/centos/7.7.1908/`. As a result, it is not reasonable to create a mirror of only CentOS 7.8. Instead, you may consider to create one of CentOS 7.

**Comment by ZuoGuocai** [comment]
Thanks for your kindness. I try again as you mentioned above  and  sync  successfully. By the way, If I don't need a lower minor release. I want to use centos7 only in my  production environment . Is the config working  reasonable  like this?

[[mirrors]]
name = "centos"
provider = "rsync"
upstream = "rsync://mirrors.tuna.tsinghua.edu.cn/centos/7/"
use_ipv6 = false

[[mirrors]]
name = "centos"
provider = "rsync"
upstream = "rsync://mirrors.tuna.tsinghua.edu.cn/centos/7.8.2003/"
use_ipv6 = false
