### ISSUE TITLE
求一份arm32位的tunasync

### ISSUE THREAD

**Issue by nn-lang** [tuna/tunasync#129]
编译过程挺简单的，自己还是个高中生实在没时间买软路由然后就想了好多种办法但都失败了。希望好心人给一份编译好的arm32位的tunasync。我将非常感谢

**Comment by Harry-Chen** [comment]
`GOARM=7 GOARCH=arm go build` 即可？

**Comment by nn-lang** [comment]
我再想想办法吧。我尝试给树莓派刷入openwrt系统翻墙后编译，希望这样做可以成功

**Comment by jiegec** [comment]
可以尝试在电脑上直接交叉编译

**Comment by Harry-Chen** [comment]
> 我再想想办法吧。我尝试给树莓派刷入openwrt系统翻墙后编译，希望这样做可以成功

go 自带交叉编译，使用我上面说的命令即可。
