### ISSUE TITLE
经常报错

### ISSUE THREAD

**Issue by canghaiwuhen** [tuna/tunasync#132]
mirror:~# unexpected fault address 0x7fe22c1de040
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7fe22c1de040 pc=0x99b1cb]

goroutine 173 [running]:
runtime.throw(0xb42c83, 0x5)
        /opt/hostedtoolcache/go/1.13.12/x64/src/runtime/panic.go:774 +0x72 fp=0xc0000565b8 sp=0xc000056588 pc=0x430e62
runtime.sigpanic()
        /opt/hostedtoolcache/go/1.13.12/x64/src/runtime/signal_unix.go:391 +0x455 fp=0xc0000565e8 sp=0xc0000565b8 pc=0x4469c5
github.com/boltdb/bolt.(*DB).meta(0xc0002501e0, 0xc0000a2040)
        /home/runner/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/db.go:811 +0x3b fp=0xc000056638 sp=0xc0000565e8 pc=0x99b1cb
github.com/boltdb/bolt.(*Tx).init(0xc00028c2a0, 0xc0002501e0)
        /home/runner/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/tx.go:50 +0x88 fp=0xc0000566a0 sp=0xc000056638 pc=0x9a1538
github.com/boltdb/bolt.(*DB).beginTx(0xc0002501e0, 0xa, 0x1, 0x48)
        /home/runner/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/db.go:486 +0x121 fp=0xc000056710 sp=0xc0000566a0 pc=0x999ce1
github.com/boltdb/bolt.(*DB).Begin(0xc0002501e0, 0xc000056700, 0xc000046a80, 0x7fe22c23ed98, 0x0)
        /home/runner/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/db.go:463 +0x6e fp=0xc000056740 sp=0xc000056710 pc=0x999b8e
github.com/boltdb/bolt.(*DB).View(0xc0002501e0, 0xc0000567f0, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/db.go:613 +0x42 fp=0xc0000567c8 sp=0xc000056740 pc=0x99a582
github.com/tuna/tunasync/manager.(*boltAdapter).GetWorker(0xc000225b40, 0xc00012203e, 0xd, 0xb416a0, 0x2, 0xc00012203e, 0xd, 0x109cc01, 0x432c5c, 0xc000056870, ...)
        /home/runner/work/tunasync/tunasync/manager/db.go:87 +0x88 fp=0xc000056820 sp=0xc0000567c8 pc=0x9a7448
github.com/tuna/tunasync/manager.(*Manager).workerIDValidator(0xc000227d00, 0xc0002da000)
        /home/runner/work/tunasync/tunasync/manager/middleware.go:25 +0xa3 fp=0xc0000568c0 sp=0xc000056820 pc=0x9a7fa3
github.com/tuna/tunasync/manager.(*Manager).workerIDValidator-fm(0xc0002da000)
        /home/runner/work/tunasync/tunasync/manager/middleware.go:23 +0x34 fp=0xc0000568e0 sp=0xc0000568c0 pc=0x9b05e4
github.com/gin-gonic/gin.(*Context).Next(0xc0002da000)
        /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 +0x3b fp=0xc000056900 sp=0xc0000568e0 pc=0x90898b
github.com/tuna/tunasync/manager.contextErrorLogger(0xc0002da000)

清除过manager.db
还这样

**Comment by z4yx** [comment]
由于BoltDB停止维护，该问题得不到修复，我们已打算切换到redis数据库。
您可以下载最新版本，并按照 https://github.com/tuna/tunasync/blob/master/docs/zh_CN/get_started.md 中的提示将tunasync的数据库换为redis。

**Comment by canghaiwuhen** [comment]
> 由于BoltDB停止维护，该问题得不到修复，我们已打算切换到redis数据库。
> 您可以下载最新版本，并按照 https://github.com/tuna/tunasync/blob/master/docs/zh_CN/get_started.md 中的提示将tunasync的数据库换为redis。

好的
