### ISSUE TITLE
adoptopenjdk sha256 not match

### ISSUE THREAD

**Issue by wangyonghong** [tuna/tunasync#145]
official 
url https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.9%2B11.1/OpenJDK11U-jdk_x64_mac_hotspot_11.0.9_11.pkg
sha256 0053a470787ed680a94e22d608a5abc731fa202c01bc0b11e5ff95d90aae6034

tuna 
url https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/11/jdk/x64/mac/OpenJDK11U-jdk_x64_mac_hotspot_11.0.9_11.pkg
sha256 aad2e32d0bd9a2170dc2244d590fcd571f660839fe4ccc971114dfd2d2968f01

**Comment by shankerwangmiao** [comment]
经查，该文件近期被上游更新，因此出现了不一致的现象。AdoptOpenJDK 的同步频率较低，请耐心等待。另查明，目前在服务器上的安装包文件的数字签名是完好的，未经篡改，请您放心使用。
