### ISSUE TITLE
[manager] Not keeping alphabetical order in /jobs API

### ISSUE THREAD

**Issue by billchenchina** [tuna/tunasync#148]
https://github.com/tuna/tunasync/blob/a54c969081b3b3089d18419c5364b0d8f270f9ab/manager/db.go#L220

**Comment by shankerwangmiao** [comment]
https://github.com/tuna/mirror-web/blob/11126c5ae27b5e8dbd5dbdee1fc4ba95c5252106/static/js/index.es6#L98

**Comment by shankerwangmiao** [comment]
所以就在前端排序一下吧。。。。
