### ISSUE TITLE
Cgroup v2 Support

### ISSUE THREAD

**Issue by shankerwangmiao** [tuna/tunasync#155]
RT.

Current status: tunasync uses libcgroup to create/del cgroups. It seems that libcgroupv2 supports cgroupv2 after its 2.0 version. However, when killing a cgroup, tunasync needs to read out all process and the interface has been changed.

**Comment by bigeagle** [comment]
How about an architectural upgrade? Fully utilize containers and change the overall arch to an FAAS scheme?
