### ISSUE TITLE
日志中出现 rsync: link "xxx" => failed: Operation not permitted 

### ISSUE THREAD

**Issue by shitou1992** [tuna/tunasync#156]
你好，我这边发现日志中有如下报错：
rsync: link "xxx" => failed: Operation not permitted 
这个该如何解决；可以通过修改rsync的参数重新编译解决吗

**Comment by shitou1992** [comment]
![image](https://user-images.githubusercontent.com/15034979/123190141-9cde4d80-d4d1-11eb-9465-8843ef9dca3b.png)

**Comment by shitou1992** [comment]
报错截图如上

**Comment by shankerwangmiao** [comment]
您好，您同步的目标文件系统是不是不支持软/硬链接？

**Comment by shitou1992** [comment]
支持的

**Comment by shitou1992** [comment]
![image](https://user-images.githubusercontent.com/15034979/123192545-bbdede80-d4d5-11eb-8eb3-c861946e1a15.png)

**Comment by shankerwangmiao** [comment]
建议您检查 selinux 相关设定。
