### ISSUE TITLE
tunasync是如何调用使用tunathu/ftpsync的

### ISSUE THREAD

**Issue by alex1528** [tuna/tunasync#158]

**Comment by Harry-Chen** [comment]
请参见下列代码

https://github.com/tuna/tunasync/blob/38a94758d209a45767864d19b19a1ebfc4db500b/worker/runner.go#L36-L67

**Comment by shankerwangmiao** [comment]
配置参见：

https://github.com/tuna/tunasync/blob/38a94758d209a45767864d19b19a1ebfc4db500b/docs/zh_CN/workers.conf#L182-L194
