### ISSUE TITLE
make it static link

### ISSUE THREAD

**Issue by hxsf** [tuna/tunasync#160]
now, this release exec need glibc.
I want to use it in alpine linux, which use musl instead of glibc. It doesn't work unless build from source.

so, I think we can add ldflags to go build, and make it static link the libc.

I create a pr #159 .

**Comment by shankerwangmiao** [comment]
I suggest that a musl version can be built along with the glibc version if you really in need of that.

**Comment by hxsf** [comment]
@shankerwangmiao 

Yes, Build two binary can cover my case.
