### ISSUE TITLE
getcodium, a project which installs codium from mirrors

### ISSUE THREAD

**Issue by larryw3i** [tuna/tunasync#161]
Is there any interest in it? I want you to improve my project together, although I am not good at maintenance, and I do not have much experience, and that is why I want to get everyone's help. Thanks a lot!  
[https://github.com/larryw3i/getcodium](https://github.com/larryw3i/getcodium)

**Comment by phy25** [comment]
I don't think GitHub issues is usually the right place to solicit for your project, especially this repo is about a mirror software on the server end rather than on the client end.
