### ISSUE TITLE
"Generating global index page" too slow when mirroring pypi with tunasync

### ISSUE THREAD

**Issue by r00t1900** [tuna/tunasync#167]
## Description

I've been mirroring pypi for about one month and finally it finished all its downloads today. Now it comes with "Generating global index page. (mirror.py: 483)" lasting for more than 1 hour. And following its hint I go to the `mirror.py:483` in bandersnatch code, just some ordinary html file writing code.

## Questions

- The cpu usage is 0.7-2.0%, is it ok?
- The memory usage is about 500M, is it ok?
- For an entire pypi mirror, how many time will this step take? and for the increment mirroring?

## Evidences

**mirroring stat**

![image](https://user-images.githubusercontent.com/57323846/158294054-53879b15-9910-4bc1-b144-3f07b68607dc.png)

> I've restart server for serveral times so the "UpTime" can not represent anything.

**worker-pypi.conf**

```nginx
[global]
name = "pypi_worker"
log_dir = "/data/tunasync/log/tunasync/{{.Name}}"
mirror_dir = "/data/tunasync"
concurrent = 10
interval = 1

[docker]
enable = true
volumes = ["/root/scripts:/home/scripts:ro"]

[manager]
api_base = "http://localhost:12345"
token = ""
ca_cert = ""

[cgroup]
enable = false
base_path = "/sys/fs/cgroup"
group = "tunasync"

[server]
hostname = "localhost"
listen_addr = "127.0.0.1"
listen_port = 6000
ssl_cert = ""
ssl_key = ""

[[mirrors]]
name = "pypi"
provider = "command"
upstream = "https://pypi.org/"
command = "/home/scripts/pypi.sh"
docker_image = "tunathu/bandersnatch:latest"
interval = 5
```

**scripts/pypi.sh**

```bash
#!/bin/bash
set -e
BANDERSNATCH=${BANDERSNATCH:-"/usr/local/bin/bandersnatch"}
TUNASYNC_UPSTREAM=${TUNASYNC_UPSTREAM_URL:-"https://pypi.org/"}
CONF="/tmp/bandersnatch.conf"
INIT=${INIT:-"0"}

if [ ! -d "$TUNASYNC_WORKING_DIR" ]; then
        mkdir -p $TUNASYNC_WORKING_DIR
        INIT="1"
fi

echo "Syncing to $TUNASYNC_WORKING_DIR"

if [[ $INIT == "0" ]]; then
(
        cat << EOF
[mirror]
directory = ${TUNASYNC_WORKING_DIR}
master = ${TUNASYNC_UPSTREAM}
json = true
timeout = 300
workers = 5
hash-index = false
stop-on-error = false
delete-packages = true
compare-method = stat
download-mirror = https://pypi.tuna.tsinghua.edu.cn/
download-mirror-no-fallback = false

[plugins]
enabled = blocklist_project

[blocklist]
packages =
  tf-nightly
  tf-nightly-gpu
  tf-nightly-cpu
EOF
        for i in $PYPI_EXCLUDE; do
                echo "    $i"
        done
) > $CONF
        exec $BANDERSNATCH -c $CONF mirror 
else
        cat > $CONF << EOF
[mirror]
directory = ${TUNASYNC_WORKING_DIR}
master = ${TUNASYNC_UPSTREAM}
json = true
timeout = 15
workers = 10
hash-index = false
stop-on-error = false
delete-packages = false
EOF

        exec $BANDERSNATCH -c $CONF mirror
fi
```

**Comment by shankerwangmiao** [comment]
Depending on the performance of your storage system, it can take several hours if it is stored on an HDD based storage system.

**Comment by r00t1900** [comment]
> Depending on the performance of your storage system, it can take several hours if it is stored on an HDD based storage system.

Wow...serveral hours...

Here is, my storage system is an RAID-5 External Storage Tank connected by USB3.0. I would like to know a little more:

- is **it takes serveral hours** happens after the initially full mirroring? And is that a real number came out from https://pypi.tuna.tsinghua.edu.cn/simple 's practice? 
- how about the time usage when it come to the incremental mirroring job in the latter days?

I would appreciate it if you could help me figure it out.

**Comment by shankerwangmiao** [comment]
Yes, it can also take long on incremental update. Several hours is an estimate since we are storing pypi on NVMe SSDs. Based on your situation, I expect an even longer time.

The whole time an incremental update takes depends on many factors, including the performance of your storage system and networking and is thus hard to estimate.

**Comment by r00t1900** [comment]
But I found the tuna mirror status, which shows that pypi is last successfully sync 5 minutes ago.So even a very little incremental update will take several hours to update index page? That is pretty bad about the design of bandersnatch.Or, the web status does not mean that and use another display strategy?

**Comment by shankerwangmiao** [comment]
The generation of the index page on an incremental update can sometimes take long and I cannot figure out why. However, sometimes the generation takes about 10 minutes or so. It depends on the performance of your storage.  

On the status page of TUNA mirror site, ``last successfully sync 5 minutes ago" means the end of the last sync is at 5 minutes ago.

**Comment by r00t1900** [comment]
Completely understood. The 5 minutes ago actually is from when the index page is generated.But, why it depends on the performance of storage system? and vary from time to time, sometimes hours sometimes 10 minutes. I mean, isn't it a normal text file writing operation? However I did not find the CPU usage of memory usage go higher, just find the status very peaceful...do not know whether it is stalled or not.Anyway, thank you for the professional answer. bravo.

**Comment by shankerwangmiao** [comment]
Because generating index page requires iterating the `simple/` directory, which contains many files and is thus an io-intensive operation.

**Comment by r00t1900** [comment]
Reasonable, it is an Io-intensive operation. Thanks!

**Comment by r00t1900** [comment]
> Because generating index page requires iterating the `simple/` directory, which contains many files and is thus an io-intensive operation.

![image](https://user-images.githubusercontent.com/57323846/158343434-0b564f85-130c-4d4a-8071-c29176f77890.png)

It appears that 4 hours are required on my HDD storage system. So now I decide to change the interval in `pypi-worker.conf`, which is from 5 to 86400, to reduce heavy load on IO of storage system.
