### ISSUE TITLE
使用代理配置后连接一直403

### ISSUE THREAD

**Issue by hutao96** [tuna/tunasync#175]
![ed023820f6c18b5358beda083dc3ebc](https://user-images.githubusercontent.com/58452268/194837272-9dca0fe5-7069-4b0d-847d-bd1f0aee769d.jpg)

**Comment by shankerwangmiao** [comment]
您具体是如何配置的？

**Comment by hutao96** [comment]
![3d6635e2ad4b51f9f6033a6293431f2](https://user-images.githubusercontent.com/58452268/194838175-201ae741-defe-4ad5-9d89-49b74e66892a.png)

**Comment by shankerwangmiao** [comment]
如果您直接执行命令：

```shell
RSYNC_PROXY="192.168.52.40:18081" rsync "rsync://mirrors.tuna.tsinghua.edu.cn/centos/"
```

会得到什么结果？

**Comment by hutao96** [comment]
![af1bf166c14bd6ea5f66f3235840a77](https://user-images.githubusercontent.com/58452268/194846357-ff94c355-9b0b-43d6-81e6-2c5939ab27f7.png)

**Comment by shankerwangmiao** [comment]
您好，既然该命令的输出与您在日志中看到的一致，说明不是 tunasync 的问题。建议您检查代理服务器的配置。

**Comment by hutao96** [comment]
好的，我们再看下，谢谢。
