### ISSUE TITLE
求帮助，truenas-core系统下如何build？

### ISSUE THREAD

**Issue by waterloo3122** [tuna/tunasync#183]
操作系统 TrueNAS-core-13.0-U2，应该是在freebsd 13.0-U2基础上进行二次开发的
如何在这个系统下build二进制可执行文件？

错误信息：
`cd /opt/tunasync/tunasync-0.8.0`
执行 `make all` 报错如下：
```
make: don't know how to make %. Stop

make: stopped in /opt/tunasync/tunasync-0.8.0
```

**Comment by shankerwangmiao** [comment]
您可以尝试手工使用 `go build` 命令编译。由于 BSD 系统的 make 与 GNU 的不同，Makefile 有可能工作不正常。

理论上 tunasync 或许能够在 BSD 系统下工作，但是我们不提供这样的保证和支持。
