### ISSUE TITLE
同步如何排除指定架构

### ISSUE THREAD

**Issue by isyekong** [tuna/tunasync#186]
您好，我想同步 Debian 的源，我想仅同步 Debian 10 / 11 的，且不同步 mips / mips64el / mipsel 架构，应该如何实现？

**Comment by ZenithalHourlyRate** [comment]
我可以提供两种方法供您参考

1. 使用 [apt-sync.py](https://github.com/tuna/tunasync-scripts/blob/master/apt-sync.py) 同步指定版本和架构
2. 由于 /debian/pool 中的包名往往包含架构与版本号，例如 [glibc](https://mirrors.cernet.edu.cn/debian/pool/main/g/glibc/)，可以在 rsync exclude_file 中通过正则表达式过滤 mips 与旧版本
