### ISSUE TITLE
使用command方式同步，如何正确获取同步到的Size？

### ISSUE THREAD

**Issue by jm0477** [tuna/tunasync#194]
问题： 
我使用apt-sync.py来同步特定的debian版本和架构，但是同步完 tunasynctl list --all 没有看到Size被更新。
我看到size_pattern是通过匹配得到。但是apt-sync.py 脚本的输出没有包含这个。应该如何获取到正确的Size呢？

翻了tunasync-scripts和tunasync的issues没有找到思路，还请帮忙提示一下，多谢！

我的worker.conf配置：
[[mirrors]]
name = "debian"
provider = "command"
upstream = "http://mirrors.ustc.edu.cn/debian/"
command = "tunasync-scripts/apt-sync.py http://mirrors.ustc.edu.cn/debian buster,bullseye,bookworm contrib,main,non-free amd64 /data/mirrors/debian --delete"
memory_limit = "256M"
interval = 1440
size_pattern = "Total size is ([0-9\\.]+[KMGTP]?)"

附：
手动执行 tunasync-scripts/apt-sync.py http://mirrors.ustc.edu.cn/debian buster,bullseye,bookworm contrib,main,non-free amd64 /data/mirrors/debian --delete
获取到的结尾部分的输出：
Skipping pool/non-free/z/zangband/zangband-data_2.7.5pre1-14_all.deb, size 919668
Skipping pool/non-free/z/znuny/otrs2_6.5.1-1_all.deb, size 11918588
moving /data/mirrors/debian/dists/bookworm/non-free/binary-amd64/.tmp/Packages.gz to /data/mirrors/debian/dists/bookworm/non-free/binary-amd64
moving /data/mirrors/debian/dists/bookworm/non-free/binary-amd64/.tmp/Packages.xz to /data/mirrors/debian/dists/bookworm/non-free/binary-amd64
moving /data/mirrors/debian/dists/bookworm/non-free/binary-amd64/.tmp/Release to /data/mirrors/debian/dists/bookworm/non-free/binary-amd64
moving /data/mirrors/debian/dists/bookworm/non-free/.tmp/Contents-amd64.gz to /data/mirrors/debian/dists/bookworm/non-free
moving /data/mirrors/debian/dists/bookworm/.tmp/InRelease to /data/mirrors/debian/dists/bookworm
moving /data/mirrors/debian/dists/bookworm/.tmp/Release to /data/mirrors/debian/dists/bookworm
moving /data/mirrors/debian/dists/bookworm/.tmp/Release.gpg to /data/mirrors/debian/dists/bookworm
Mirroring http://mirrors.ustc.edu.cn/debian bookworm, non-free, amd64 done!
716 packages, 7700201380 bytes in total

**Comment by shankerwangmiao** [comment]
您好，`apt-sync.py` 并非用于 tunasync 直接调用，而是需要另有脚本调用 `apt-sync.py`，然后由其计算出总大小。

您可以参考：

https://github.com/tuna/tunasync-scripts/blob/1a6b3f6add3dd75550488f13209d07b37d9fe692/llvm-apt.sh#L33
https://github.com/tuna/tunasync-scripts/blob/1a6b3f6add3dd75550488f13209d07b37d9fe692/influxdata.sh#L33
