### ISSUE TITLE
是否需要更换更快的GoWeb框架

### ISSUE THREAD

**Issue by Fgaoxing** [tuna/tunasync#196]
如题，Gin在[https://www.techempower.com/benchmarks/](https://www.techempower.com/benchmarks/)不算靠前（其中有些不是HTTP实现），在速度上这很致命（我没有推荐自己写的的意思，那个还不成熟）

**Comment by shankerwangmiao** [comment]
目前而言，HTTP 通信仅涉及 tunasynctl 客户端、worker 和 manager 之间的控制消息。其数量和频率都十分有限。前台展示的 tunasync.json 来源于 manager，但是该数据在 nginx 上是有缓存的。因此目前 http 通信框架的性能是满足要求的。
