### ISSUE TITLE
如何将job日志合并到worker输出中

### ISSUE THREAD

**Issue by jimorsm** [tuna/tunasync#197]
如何将job日志合并到worker输出中

**Comment by shankerwangmiao** [comment]
这个功能无法支持。因为如果将 job 的日志合并于 worker 的输出，则会造成多个 job 的日志混杂在一起，无法区分具体是哪个 job 的输出。

**Comment by jimorsm** [comment]
为何不能增加标识例如:
[24-01-xx xx:xx:xx][NOTICE][JOB1] JOB1 LOG CONTENT
[24-01-xx xx:xx:xx][NOTICE][JOB2] JOB2 LOG CONTENT

**Comment by shankerwangmiao** [comment]
> 为何不能增加标识例如:
> 
> [24-01-xx xx:xx:xx][NOTICE][JOB1] JOB1 LOG CONTENT
> 
> [24-01-xx xx:xx:xx][NOTICE][JOB2] JOB2 LOG CONTENT

这是因为同步任务的日志输出，是由具体的同步工具/脚本产生，tunasync 无法控制其内容，也不能修改其格式。
