### ISSUE TITLE
CentOS 的源怎么就突然没有了

### ISSUE THREAD

**Issue by atomsos** [tuna/tunasync#199]
RT，https://mirrors.tuna.tsinghua.edu.cn/centos/7/里面只剩下了readme，也没有新闻公告也没有issue

**Comment by shankerwangmiao** [comment]
您好，CentOS 7 已于 6 月 30 日停止支持，其软件仓库也相应被上游移除。TUNA 按原样提供软件仓库的镜像，因此也随之移除了 CentOS 软件仓库中的软件包。
