### ISSUE TITLE
tunasync怎么配置网络代理

### ISSUE THREAD

**Issue by bystp** [tuna/tunasync#201]
内网通过代理上网，配置环境变量http_proxy，http_proxy，RSYNC_PROXY都不行。

**Comment by shankerwangmiao** [comment]
您好，该问题需要视您的具体使用情况而定。

如果您配置的同步任务是 rsync 任务，您需要参考 rsync 的文档，使用 `RSYNC_PROXY` 或 `RSYNC_CONNECT_PROG` 环境变量指定代理配置。其中，前者需要一个 HTTP 代理，并且要求该代理允许客户端连接至远程 rsync 服务器的提供 rsync 服务的端口（默认为 873）；后者则是可以提供一个自定义的用于创建 rsync 连接的命令，二者的具体格式请参考 rsync 文档。在 tunasync 的配置文件中，为一个 rsync 同步任务指定环境变量的方法是，在相应的 `[[mirrors]]` 小节中，增加 `[mirrors.env]` 小节，并在其中增加形如 `ENV = "value"` 的配置项。

如果您配置的同步任务使用的是自定义的同步命令或脚本，您需要参考该脚本的具体工作方式，向其传入代理的配置。使用自定义命令进行同步的任务，同样支持 `[mirrors.env]` 配置项，用于定义向该命令传入的环境变量。但是，您必须确认该同步脚本或工具能够接受并识别您传入的环境变量。
