### ISSUE TITLE
Android SDK

### ISSUE THREAD

**Issue by bigeagle** [tuna/tunasync#4]
参考:

https://dl.google.com/android/repository/repository-10.xml
http://mirrors.neusoft.edu.cn/android/repository/

**Comment by bigeagle** [comment]
https://dl-ssl.google.com/android/repository/addons_list-2.xml

**Comment by huiyiqun** [comment]
这是要给Android SDK做mirror？

**Comment by bigeagle** [comment]
恩，最近有两个人提 issues 想要了。目测国内对 Android SDK 的需求比 AOSP 更大些

**Comment by huiyiqun** [comment]
嘛 那就干吧 好像是有example了 你动手？

**Comment by bigeagle** [comment]
我想搞成 pypi 的同步那样的，lftp 从 neusoft 下不是不可以，感觉不太好。

可能开一个独立项目比较合适？我看了下，就是把那两个 xml 下下来，里面的 url 抓出来download了就可以。这样放个命令行到 scripts 里，tunasync 就可以管理。

@huiyiqun 你先试试？我最近赶论文……

**Comment by huiyiqun** [comment]
那我来吧

**Comment by bigeagle** [comment]
issues 里有两个相关的 ticket，你去 take 一下？

**Comment by hosiet** [comment]
虽说做 Android SDK Mirror 是好事，不过请注意一下：

3.3 You may not use the SDK for any purpose not expressly permitted by this License Agreement. Except to the extent required by applicable third party licenses, you may not: (a) copy (except for backup purposes), modify, adapt, **redistribute**, decompile, reverse engineer, disassemble, or create derivative works of the SDK or any part of the SDK; ...

https://developer.android.com/sdk/terms.html

**Comment by huiyiqun** [comment]
我终于明白Android Developer们在纠结什么了。

http://my.oschina.net/u/1395677/blog/175124

Android Studio不支持mirror，只支持proxy，所以他们希望我们作为proxy来下载Google SDK（当然我们会伪装成Proxy给他们提供文件）。

我们mirror AOSP是没问题的，但是这样Proxy SDK是否真的合适？ @bigeagle

**Comment by bigeagle** [comment]
卧X……

On Thu, Jan 22, 2015 at 1:21 PM, Boyuan Yang <notifications@github.com>
wrote:

> 虽说做 Android SDK Mirror 是好事，不过请注意一下：
>
> 3.3 You may not use the SDK for any purpose not expressly permitted by
> this License Agreement. Except to the extent required by applicable third
> party licenses, you may not: (a) copy (except for backup purposes), modify,
> adapt, *redistribute*, decompile, reverse engineer, disassemble, or
> create derivative works of the SDK or any part of the SDK; ...
>
> https://developer.android.com/sdk/terms.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tuna/tunasync/issues/4#issuecomment-70973033>.
>



-- 
Open Source, Open Mind

**Comment by alick9188** [comment]
wontfix 吧？

**Comment by bigeagle** [comment]
Agree.
