### ISSUE TITLE
报错: Error initializing DB adapter: open /var/lib/tunasync/tunasync.db: no such file or directory

### ISSUE THREAD

**Issue by scateu** [tuna/tunasync#42]
(sid)scateu@localhost:~$ ./tunasync --help
NAME:
   tunasync - A new cli application

USAGE:
   tunasync [global options] command [command options] [arguments...]

VERSION:
   0.1

COMMANDS:
     manager, m  start the tunasync manager
     worker, w   start the tunasync worker

GLOBAL OPTIONS:
   --help, -h     show help
   --version, -v  print the version

(sid)scateu@localhost:~$ ./tunasync manager
[16-10-31 00:16:51][ERROR] Error initializing DB adapter: open /var/lib/tunasync/tunasync.db: no such file or directory
[16-10-31 00:16:51][ERROR] Error intializing TUNA sync worker.

**Comment by scateu** [comment]
手动touch了一下那个.db文件起起来了。

**Comment by bigeagle** [comment]
康哥…… 你这是在刷 issue 么……
