### ISSUE TITLE
make scripts a submodule to tunasync-scripts

### ISSUE THREAD

**Issue by huiyiqun** [tuna/tunasync#49]
Currently, scripts directory is some legacy content of [tunasync-scripts](https://github.com/tuna/tunasync-scripts). It's confusing to users.

How about making it a submodule pointed to tunasync-scripts?

**Comment by bigeagle** [comment]
I'd prefer deleting it.

**Comment by huiyiqun** [comment]
It's better to remove it now and discuss this problem later.

**Comment by bigeagle** [comment]
deleted in 03d22b7683f644b986902a669a343bb8d99dafcf
