### ISSUE TITLE
How to solve bandersnatch via proxy?

### ISSUE THREAD

**Issue by modoojunko** [tuna/tunasync#5]
HI，

I know this is not one "bug".But I noticed that tuna also uses the bandersnatch to sync Pypi .
I use the same way in my company, but the different is that ,my company has proxy. Each time I execute bandersntach will be failed by the connection time out.

Do you have any ideas?

**Comment by huiyiqun** [comment]
We are neither the developers of bandersnatch or familiar with this project.

Maybe [here](https://bitbucket.org/pypa/bandersnatch/) is a good place to request for help.

**Comment by modoojunko** [comment]
I have solved this, xmlrpc lib should add proxy part
