### ISSUE TITLE
没办法同步，希望得到帮助

### ISSUE THREAD

**Issue by guliujian** [tuna/tunasync#50]
manager 收到worker 的信息，但worker 似乎没有执行mirrors里边的同步脚本，按照中文教程执行了几遍，也换过几台服务器，都不行，希望能够得到帮助。

**Comment by shankerwangmiao** [comment]
worker 有什么日志输出吗？

**Comment by guliujian** [comment]
worker 什么日志都没有输出，就算开了debug 模式 
![image](https://cloud.githubusercontent.com/assets/10088700/20456102/4f699946-aea8-11e6-9453-9d0668188a1d.png) 
这是worker 上面开了debug模式的，然后也不执行mirrors里边的脚本
![image](https://cloud.githubusercontent.com/assets/10088700/20456100/3d29c2a6-aea8-11e6-9d53-74a151b00e7c.png)
这个是manager的信息 
![image](https://cloud.githubusercontent.com/assets/10088700/20456110/668428e4-aea8-11e6-99d0-570eeff5d985.png)
配置文件都按照中文教程的复制粘贴

**Comment by shankerwangmiao** [comment]
您看一下 a.json  有没有内容？

**Comment by guliujian** [comment]
a.json 没有任何内容，我看了一下manager.db 
![image](https://cloud.githubusercontent.com/assets/10088700/20456136/3bf0dc34-aea9-11e6-877e-ae05d3f3265b.png)
这边有连接上的信息

**Comment by shankerwangmiao** [comment]
这就奇怪了。

你试试执行 tunasynctl reload -w test_worker ，看看 manager 和 worker 都有什么输出。

另外看看 syslog 里有没有什么日志啥的。

这个工具嘛，似乎对部分不合理的配置的检查不充分，有些地方出了错误不报告，略坑。

**Comment by guliujian** [comment]
这次报这个错误
![image](https://cloud.githubusercontent.com/assets/10088700/20456171/388307e2-aeaa-11e6-9398-20113530826d.png)感觉问题可能在这？

**Comment by bigeagle** [comment]
workers里的内容呢？

**Comment by guliujian** [comment]
没有任何变化，感觉就像没执行过任何东西一样

**Comment by bigeagle** [comment]
我是说，让我看一下worker.conf里的内容……

**Comment by guliujian** [comment]
很抱歉理解错了，
![image](https://cloud.githubusercontent.com/assets/10088700/20456340/faec50ae-aeaf-11e6-9df3-e57fa088ff99.png)
按照中文文档跑的

**Comment by bigeagle** [comment]
最下面改成 `include_mirrors = "/home/xxxx/tunasync_demo/mirrors/*.conf"` 试试

**Comment by guliujian** [comment]
改了之后还是没有用，manager 和worker都重启了一下

**Comment by bigeagle** [comment]
…… 这种情况我还没遇到过

**Comment by guliujian** [comment]
今天也换了几台测试了一下发现都不行，我也觉得很奇怪，每个文件都是按照文档里复制的

**Comment by bigeagle** [comment]
![deepinscreenshot20161119234620](https://cloud.githubusercontent.com/assets/548512/20456486/64b5f1fa-aeb2-11e6-814d-f21dfba25071.png)

不要那个 include 了，直接把 elvish.conf 里的内容贴进 worker.conf 里也是可以的，无论怎么搞，一定都会有 job 加入进来。你这儿没有 job 加入的信息，就是没有被正确地 include。 manager 都可以不用跑，那个 WARNING 不用管。

**Comment by guliujian** [comment]
我把文件中的include 删掉之后，然后复制进来mirror的那个就能跑了，那应该就是include的问题了，感谢帮助
