### ISSUE TITLE
从日志中获得 rsync 仓库的大小

### ISSUE THREAD

**Issue by bigeagle** [tuna/tunasync#52]
refer tuna/issues#160

**Comment by shankerwangmiao** [comment]
`tac foo/latest | grep '^Total file size: ' | head -n 1 | sed 's/^Total file size: //'`

**Comment by kinosang** [comment]
will it be implemented in future release?

**Comment by bigeagle** [comment]
Yes, the code is almost ready. Likely to be implemented this weekend.

**Comment by kinosang** [comment]
Good news.

Thank you for your working.

It's more suitable than using `du`, the way I used to calculate repo size. Hope it comes asap.

**Comment by alick** [comment]
233 若干年前我们干过同样的事情

Regards,
Alick

**Comment by kinosang** [comment]
set `exec_on_success` for worker global configuration can solve this.

no need to modify the binary.

```
exec_on_success = [
    "bash -c 'tunasynctl set-size -w main_worker ${TUNASYNC_MIRROR_NAME} `tac ${TUNASYNC_LOG_FILE}  | grep \"^Total file size: \" | head -n 1 | grep -Po \"[0-9\\.]+[MGT]\"`'"
]
```

**Comment by shankerwangmiao** [comment]
已添加
