### ISSUE TITLE
`status_file` not work

### ISSUE THREAD

**Issue by kinosang** [tuna/tunasync#53]
I tried to set `status_file` in `manager.conf`, but it does not work.

I read through the sources but there's no codes for it. Does the `status_file` deprecated? Is there any way to get mirrors' status from a webpage?

**Comment by kinosang** [comment]
Is it appropriate to make a reserved proxy for `localhost:12345/jobs` for this?

**Comment by bigeagle** [comment]
yes， status_file has been removed from the latest version. We're currently using reverse proxy.
