### ISSUE TITLE
RsyncProvider has no "--links" in the default options.

### ISSUE THREAD

**Issue by cubarco** [tuna/tunasync#6]
I see that the official mirror scripts provided by Archlinux and Ubuntu both has the option "--links" in it. I'm wondering why there's no "--links" in the default options.

```python
class RsyncProvider(MirrorProvider):

    _default_options = ['-aHvh', '--no-o', '--no-g', '--stats',
                        '--exclude', '.~tmp~/',
                        '--delete', '--delete-after', '--delay-updates',
                        '--safe-links', '--timeout=120', '--contimeout=120']
...
```

**Comment by bigeagle** [comment]
`rsync`'s `-a` option equals to `-rlptgoD`, where `-l` or `--links` has
been included.

On Fri, Jul 10, 2015 at 1:25 PM, Cubarco <notifications@github.com> wrote:

> I see that the official mirror scripts provided by Archlinux and Ubuntu
> both has the option "--link" in it. I'm wondering why there's no "--links"
> in the default options?
>
> class RsyncProvider(MirrorProvider):
>
>     _default_options = ['-aHvh', '--no-o', '--no-g', '--stats',
>                         '--exclude', '.~tmp~/',
>                         '--delete', '--delete-after', '--delay-updates',
>                         '--safe-links', '--timeout=120', '--contimeout=120']
> ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tuna/tunasync/issues/6>.
>



-- 
Open Source, Open Mind

**Comment by bigeagle** [comment]
`rsync`'s `-a` option equals to `-rlptgoD`, where `-l` or `--links` has been included.

**Comment by cubarco** [comment]
Stupid me. Thanks for your quick reply.

**Comment by bigeagle** [comment]
No problem :)
