### ISSUE TITLE
同步过程中报错

### ISSUE THREAD

**Issue by hifour** [tuna/tunasync#62]
Centos7的服务器，同步过程中，报端口连接被拒绝。查看了下防火墙及SELINUX的状态都被禁用了。查看服务状态后，报错如下
systemctl status tunasync-worker.service -l

3月 06 22:09:24 p-awscn-paas tunasync[62593]: [ERROR] Failed to update mirror(centos) status: Post https://mirrors.xxxxx.com:12345/workers/mirror_worker/jobs/centos: dial tcp ip地址:12345: getsockopt: connection refused

包的确是被正常的同步下来了，但是无法使用tunasync list mirrors_worker状态查看每个包的同步状态。

**Comment by huiyiqun** [comment]
这应该是在试图向manager报告同步状态的时候出错了，确认一下你的manager是否确实运行在`mirrors.xxxxx.com`并且监听12345端口。

比如在目标机器上运行
```
~> ss -ltpn | grep 12345
```
试试？

**Comment by hifour** [comment]
ss -ltpn | grep 12345
LISTEN     0      16384  127.0.0.1:12345                    *:*                   users:(("tunasync",pid=62581,fd=4))

端口我之前测过，是通的。另外manager的状态也是正常的。还有别的可能吗？方便的话，希望能够留个联系方式交流一下。

**Comment by shankerwangmiao** [comment]
是啊，你看错误不就出在这里了嘛。你 manager 监听的时候 bind 在 127.0.0.1 上，但是你 worker 往上连的时候却用的不是  127.0.0.1 的地址，自然会出错。

如果你 manager 和 worker 是运行在同一台机器上的话，你应该在 worker 的配置里把 manager 的地址改成 127.0.0.1

**Comment by hifour** [comment]
非常感谢贵校工作组能够快速响应问题。可能之前没有说清楚，我在/etc/hosts中已经做过本地地址和域名的映射解析了，但是我还是尝试将worker.conf中的manager的配置更改如下
#由于改成127.0.0.1之后，[ERROR] Failed to fetch job status: Get 127.0.0.1:12345/workers/mirror_worker/jobs: unsupported protocol scheme "" 所以采用以下的配置方式
[manager]
api_base = "http://127.0.0.1:12345"     
ca_cert = "/etc/tunasync/rootCA.crt"

但是报错依然存在
Failed to update mirror(mongodb) status: Post http://127.0.0.1:12345/workers/mirror_worker/jobs/mongodb: malformed HTTP response "\x15\x03\x01\x00\x02\x02\x16"

manager的配置信息如下：
debug = false
[server]
addr = "127.0.0.1"
port = 12345
ssl_cert = "/etc/tunasync/host.crt"
ssl_key = "/etc/tunasync/host.key"

[files]
db_type = "bolt"
db_file = "/opt/tunasync/manager.db"
ca_cert = "/etc/tunasync/rootCA.crt"

**Comment by hifour** [comment]
另外由于我使用apache做的前端web通过SSL加密协议，因此之前配置的api_base=https://mirrors.xxxxxx.com。
使用curl去连接的过程中
curl https://mirrors.xxxxxx.com:12345/workers 提示拒绝链接
curl https://mirrors.xxxxxx.com/workers则报404 error。望回复。

**Comment by shankerwangmiao** [comment]
把 api_base 改成 https 试试？

发自我的 iPhone

**Comment by huiyiqun** [comment]
其实我更建议根据 https://github.com/tuna/tunasync/blob/master/docs/zh_CN/get_started.md 把`ssl_cert`和`ssl_key`都设成空字符串，然后使用http协议。

在本机通信还使用ssl增加了复杂度，也没什么实质意义。

**Comment by hifour** [comment]
Get /workers/mirror_worker/jobs: unsupported protocol scheme "" 我猜想是域名SSL认证这块有问题

请教一下
[manager]的配置信息中关于token这项该怎么进行配置？token的生成通过什么来做

**Comment by huiyiqun** [comment]
如果可以最好贴一下完整的配置文件，方便我们复现问题。

**Comment by hifour** [comment]
@huiyiqun 之前没有理解SSL证书的配置含义具体是干嘛用的，因此按照文档生成并添加到了配置文件中。才知道原来证书是在不同服务器做交互的时候做认证用的，刚把证书全注销掉之后，问题已经解决。非常感谢耐心指导。
