### ISSUE TITLE
How to configure the sync time with different jobs?

### ISSUE THREAD

**Issue by jammary** [tuna/tunasync#72]
Hello,  the server's disk I/O is alway very high when tunasync syncs mirrors, so we want to setup different sync times for these mirrors sync jobs, coud you tell me how to configure it.

**Comment by shankerwangmiao** [comment]
You can limit the concurrent running jobs by setting `concurrent = 10` in worker.conf

**Comment by shankerwangmiao** [comment]
If you want to specify a time for a job (eg. start syncing at 01:00 everyday), it is not supported by tunasync now.

**Comment by shankerwangmiao** [comment]
However, we are running a modified version of rsync daemon to reduce disk I/O for providing service. For detail, please visit https://github.com/tuna/rsync/blob/master/README-huai.md
