### ISSUE TITLE
同步问题

### ISSUE THREAD

**Issue by shengliang1984** [tuna/tunasync#77]
mirror远程源里的rpm包没有了，为什么我本地的rpm包也会被删除，有没有办法保留本地的rpm包

**Comment by shankerwangmiao** [comment]
您好，请具体描述故障情况，比如，使用何种方法与上游同步，同步的是什么镜像，使用的 tunasync 是什么版本编译的。

**Comment by shengliang1984** [comment]
使用tunasync与上游同步，同步的是https://mirrors.tuna.tsinghua.edu.cn/apache/这个镜像，比如说apache下面zookeeper下面有一个老版本没有了，更新了一个新的版本，比如说去掉了zookeeper-3.2.2/，然后我本来通过tunasync同步过来之后也会删除zookeeper-3.2.2/，但是我想使用tunasync更新镜像，但是不想删除本地的老的镜像， tunasync -v之后显示Version: 0.1

**Comment by shankerwangmiao** [comment]
你使用的是 rsync 吗？如果是的话，问题是出在这里， https://github.com/tuna/tunasync/blob/master/worker/rsync_provider.go#L46 ，给 rsync 传入了 `--delete` 参数，删除了上游删除的文件。请注意：这个做法是正常且必要的，如果您有特殊的需要，要保留上游删除的文件，您可以选择如下两种解决方案：1. 自行去掉该选项，重新编译 tunasync；2. 自行编写一个 wrap 脚本，被 tunasync 当作是 rsync 程序执行，该脚本从参数中抹除 delete 相关的选项，再调用真实的 rsync 程序

**Comment by shengliang1984** [comment]
哦。非常感谢，tunasync有几种同步方法，除了rsync还有什么？我是使用二进制的tunasync,他默认是使用rsync是吗？

**Comment by shengliang1984** [comment]
provider这里控制的吗?provider = "rsync"

**Comment by shankerwangmiao** [comment]
是的，我说的解决方案 2 中，wrap 脚本以 command 参数传入，provider 保持 rsync 不变。

**Comment by shankerwangmiao** [comment]
另外，您也可以手工编写同步脚本，此时 provider 是 command

**Comment by shengliang1984** [comment]
能具体点吗？wrap脚本能提供吗？哈哈。我是刚刚接触

**Comment by shengliang1984** [comment]
此时 provider 是 command  这个具体怎么弄呢？主要文档太少，网上都搜不到

**Comment by shengliang1984** [comment]
provider是command  那这个command可以是一个脚本吗？这样子provider = "/tmp/rsync.sh"

**Comment by shankerwangmiao** [comment]
嗯嗯， tunasync 的用法您就直接在这里问吧，搜索肯定搜索不到，这个是我们自己的工具，开源出来给大家用，但是文档很糟糕。我给你几个样例。

## 标准 rsync

```
[[mirrors]]
name = "iina"
provider = "rsync"
upstream = "rsync://link-start.iina.io/iina/"
memory_limit = "256M"
```

## 带包装脚本的 rsync

比如这个镜像，需要使用 rsync over ssh 协议，同步的时候需要提供私钥给 ssh 指令，这个需要修改传递给  rsync 命令的参数，因此使用 wrapper 脚本
```
[[mirrors]]
name = "openthos"
provider = "rsync"
upstream = "a.b.c.d:rsync/oto_img/"
memory_limit = "256M"
command = "/path/to/rsync-warpper.sh"
```

脚本里就是：

```
#/bin/bash
exec rsync --rsh="ssh -p 12345 -l username -i /path/to/id_rsa" "$@"
```

正常情况下，tunasync 会执行 `rsync -aHvh --no-o --blabla a.b.c.d:rsync/oto_img/ /path/to/mirror/`。 但是提供了 wrapper 脚本的情况下，就改为执行 `/path/to/rsync-warpper.sh-aHvh --no-o --blabla a.b.c.d:rsync/oto_img/ /path/to/mirror/`，然后由这个脚本执行 `rsync  --rsh="ssh -p 12345 -l username -i /path/to/id_rsa" --no-o --blabla a.b.c.d:rsync/oto_img/ /path/to/mirror/`。这样就起到了修改 rsync 选项的目的。更进一步地，这个脚本还可以修改传递的参数。

## 自定义脚本

```
[[mirrors]]
name = "adobe-fonts"
interval = 1440
provider = "command"
upstream = "https://github.com/adobe-fonts"
command = "/path/to/adobe-fonts.sh"
```

此时，tunasync 会直接调用脚本 `/path/to/adobe-fonts.sh`，不带任何参数，通过环境变量，将相关配置传给脚本。这个脚本在 <https://github.com/tuna/tunasync-scripts/blob/master/adobe-fonts.sh> 这里，你可以看见，`TUNASYNC_UPSTREAM_URL` `TUNASYNC_WORKING_DIR` 这些环境变量是 tunasync 传入的。

**Comment by shengliang1984** [comment]
TUNASYNC_UPSTREAM_URL这个变量对应upstream = "rsync://mirrors.tuna.tsinghua.edu.cn/centos/"
TUNASYNC_WORKING_DIR这个变量对应mirror_dir = "/data"   是吗？

**Comment by shengliang1984** [comment]
那我如何去掉用这个变量exclude_file，请高手指导

**Comment by shankerwangmiao** [comment]
对于 mirror foo，TUNASYNC_WORKING_DIR 是 /data/foo 

exclude_file 传入的是一个文件名，该文件是多行的纯文本文件，用于指明同步时需要排除的文件列表，语法详见 rsync 命令的手册。请注意，该选项仅在 provider 为 rsync 或 two-stage-rsync 时有意义。

**Comment by shengliang1984** [comment]
HI.麻烦帮忙看看我的新的问题。在最新的issue里面，谢谢

**Comment by bubbleatgit** [comment]
当 `provider = "rsync"` 时，如何同步指定版本的软件，比如 `saltstack` ，我只想要 ubuntu 18.04 的 2018.3.2 版本。 整个URI路径 `https://mirrors.tuna.tsinghua.edu.cn/saltstack/apt/ubuntu/18.04/amd64/archive/2018.3.2/` 。

我用 rsync 实现了该需求，但是感觉有点麻烦，不知道 tunasync 有没有简单点的实现方法。

```
rsync -nrlvH  --include-from=include.txt --exclude-from=exclude.txt repo.saltstack.com::saltstack_pkgrepo_full ./full_repo
```
include.txt 文件内容：
```
apt/
apt/ubuntu/
apt/ubuntu/18.04/
apt/ubuntu/18.04/amd64/
apt/ubuntu/18.04/amd64/archive/
apt/ubuntu/18.04/amd64/archive/2018.3.2/
```
exclude.txt 文件内容
```
apt/*
apt/ubuntu/*
apt/ubuntu/18.04/*
apt/ubuntu/18.04/amd64/*
apt/ubuntu/18.04/amd64/archive/*
```
