### ISSUE TITLE
how to config multiple mirror

### ISSUE THREAD

**Issue by kozora** [tuna/tunasync#83]
`[[mirrors]]

name = "ubuntu"

provider = "rsync"

upstream = "rsync://archive.ubuntu.com/ubuntu/"

use_ipv6 = true
`
this config is correct, but dont know how to add more mirror

**Comment by z4yx** [comment]
I've added some typical configurations to docs.

https://github.com/tuna/tunasync/blob/master/docs/zh_CN/workers.conf
