### ISSUE TITLE
Could you share the configuration files used behind `mirrors.tuna.tsinghua.edu.cn`

### ISSUE THREAD

**Issue by liudonghua123** [tuna/tunasync#85]
Hi, I am in a high school, and I want to build a mirror site like `mirrors.tuna.tsinghua.edu.cn` to make things convenient for downloading software or packages.

I have asked similar issue on  https://github.com/tuna/mirror-web/issues/105#issuecomment-430866045 and know that behind the scene it is the [tuna/tunasync](https://github.com/tuna/tunasync) works.

I have also read the https://github.com/tuna/tunasync/blob/master/docs/zh_CN/get_started.md, and got to know I need to write `worker.conf` and `manager.conf` to make it work. 

But this is really a lot of work something like reinvent the wheel, so could you share these configuration files publicly.

**Comment by z4yx** [comment]
https://github.com/tuna/tunasync/blob/master/docs/zh_CN/workers.conf
添加了一些镜像的配置作为示例。

进一步了解各种镜像的同步方法，请移步 https://github.com/tuna/tunasync-scripts/
