### ISSUE TITLE
tunasynctl不能指定端口

### ISSUE THREAD

**Issue by GaryH4** [tuna/tunasync#90]
tunasynctl 不能指定manager的端口，<del>钦定</del>强制使用了14242端口

**Comment by z4yx** [comment]
https://github.com/tuna/tunasync/blob/master/manager/config.go#L57

检查了一下，端口是从配置文件获取的。

**Comment by shankerwangmiao** [comment]
https://github.com/tuna/tunasync/blob/master/cmd/tunasynctl/tunasynctl.go#L31

配置文件在这个位置，分为用户的和系统的，其中用户的可以覆盖系统的，配置文件的结构在：https://github.com/tuna/tunasync/blob/master/cmd/tunasynctl/tunasynctl.go#L50

**Comment by z4yx** [comment]
已添加进文档。

**Comment by GaryH4** [comment]
不过文档没有说workerID写在哪……
![image](https://user-images.githubusercontent.com/18082932/55669905-76f80e80-58af-11e9-9f1b-99c80748c497.png)

![image](https://user-images.githubusercontent.com/18082932/55669898-6e073d00-58af-11e9-8043-fdf04ca32f97.png)
