### ISSUE TITLE
如何让 tunasync.json 更新

### ISSUE THREAD

**Issue by TerenceLiu98** [tuna/tunasync#95]
下载 tunasync.json 后 镜像列表可以显示，但是不能根据 tunasync 和 tunasynctl 的运行而更新。想问一下他的通讯方式

**Comment by TerenceLiu98** [comment]
另外，服务器监控是通过什么形式获取的😅

**Comment by z4yx** [comment]
访问  http://127.0.0.1:12345/jobs
其中12345是manager的端口

**Comment by z4yx** [comment]
服务器操作系统和硬件的监控不属于tunasync功能范围。请上网查阅 Grafana 相关教程。

**Comment by TerenceLiu98** [comment]
@z4yx 好的 感谢 🙏
