### ISSUE TITLE
Rsync no module named anaconda

### ISSUE THREAD

**Issue by lovechang1986** [tuna/tunasync#99]
请问pypi和anaconda都没有提供rsync服务吗？

**Comment by shankerwangmiao** [comment]
pypi 由于文件数过多，不提供 rsync 服务。

anaconda 的 rsync 服务已经打开了，但是根据 Anaconda Inc. 的授权，您可能不能公开地利用同步的数据提供服务。

**Comment by lovechang1986** [comment]
我需要在内网使用，不会在公网提供任何服务，谢谢，稍后我尝试一下。
